development:
  adapter: postgresql
  host: localhost
  encoding: unicode
  database: learnster_development
  pool: 5
  username: anthonytroy
  password:

test:
  adapter: sqlite3
  database: db/test.sqlite3
  pool: 5
  timeout: 5000

# Capistrano generates a seperate database.yml file
# on deploys
production:
  adapter: postgresql
  encoding: unicode
  database: learnster_production
  pool: 5
  username: anthonytroy
  password:
