development:
  adapter: postgresql
  encoding: unicode
  database: learnster_development
  pool: 5
  username: anthonytroy
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: learnster_test
  pool: 5
  username: anthonytroy
  password:

# Capistrano generates a seperate database.yml file
# on deploys
production:
  adapter: postgresql
  encoding: unicode
  database: learnster_production
  pool: 5
  username: anthonytroy
  password:
